spring.application.name=mongoDB_project

server.port=8083


spring.data.mongodb.uri=mongodb+srv://ks3729100_db_user:wyXqFUhCdeykMrH8@cluster1.jmymq0y.mongodb.net/AmazonProducts?appName=Cluster1



spring.data.redis.host=united-marmoset-124667.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAeb7AAIgcDEzYjY3NTU3ZWNiYWY0MjkxYmQ3NzRhNjBhMDRiNzE5NA
spring.data.redis.ssl.enabled=true

spring.cache.type=redis

# OPTIONAL LOGS
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG